const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");

const repoRoot = path.resolve(__dirname, "..");
const mobileEnvLocalPath = path.join(repoRoot, "apps", "mobile", ".env.local");

function isPrivateIpv4(ip) {
  const parts = ip.split(".").map(Number);
  if (parts.length !== 4 || parts.some((part) => Number.isNaN(part))) return false;
  if (parts[0] === 10) return true;
  if (parts[0] === 172 && parts[1] >= 16 && parts[1] <= 31) return true;
  return parts[0] === 192 && parts[1] === 168;
}

function isVirtualInterface(name) {
  return /wsl|hyper-v|vethernet|virtual|vmware|virtualbox|docker|loopback|bluetooth/i.test(name);
}

function scoreCandidate(candidate) {
  let score = 0;
  if (isPrivateIpv4(candidate.address)) score += 50;
  if (/wi-?fi|wireless/i.test(candidate.name)) score += 35;
  if (/ethernet|local area/i.test(candidate.name)) score += 20;
  if (candidate.address.startsWith("192.168.")) score += 12;
  if (candidate.address.startsWith("10.")) score += 8;
  if (/^172\.(1[6-9]|2\d|3[0-1])\./.test(candidate.address)) score += 4;
  if (isVirtualInterface(candidate.name)) score -= 100;
  return score;
}

function detectLanIpv4Addresses() {
  const interfaces = os.networkInterfaces();
  const candidates = [];

  for (const [name, entries] of Object.entries(interfaces)) {
    for (const entry of entries || []) {
      if (entry.family !== "IPv4" || entry.internal) continue;
      if (entry.address.startsWith("127.") || entry.address.startsWith("169.254.")) continue;
      if (!isPrivateIpv4(entry.address)) continue;
      candidates.push({
        address: entry.address,
        name,
        score: scoreCandidate({ address: entry.address, name }),
      });
    }
  }

  return candidates.sort((a, b) => b.score - a.score || a.address.localeCompare(b.address));
}

function writeMobileEnvLocal(apiUrl) {
  fs.mkdirSync(path.dirname(mobileEnvLocalPath), { recursive: true });
  fs.writeFileSync(
    mobileEnvLocalPath,
    [
      "# Generated by npm run mobile:env:lan. Do not commit this file.",
      `EXPO_PUBLIC_API_URL="${apiUrl}"`,
      'EXPO_PUBLIC_RELEASE_CHANNEL="development"',
      "",
    ].join(os.EOL),
  );
}

function main() {
  const candidates = detectLanIpv4Addresses();
  if (candidates.length === 0) {
    console.error("No private LAN IPv4 address was detected.");
    console.error("Connect to Wi-Fi or Ethernet, then rerun npm run mobile:env:lan.");
    process.exit(1);
  }

  const selected = candidates[0];
  const apiUrl = `http://${selected.address}:4000`;
  writeMobileEnvLocal(apiUrl);

  console.log("Mobile LAN env updated.");
  console.log(`- Selected API URL: ${apiUrl}`);
  console.log(`- Interface: ${selected.name}`);
  if (candidates.length > 1) {
    console.log("- Other detected private IPv4 addresses:");
    for (const candidate of candidates.slice(1)) {
      console.log(`  ${candidate.address} (${candidate.name})`);
    }
  }
  console.log("- Wrote: apps/mobile/.env.local");
  console.log("");
  console.log("Next:");
  console.log("1. npm run dev:api");
  console.log("2. npm run mobile:start:clear");
}

main();
